### ISSUE TITLE
Profile webisite links link back to profile.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#1]
**Describe the bug**
When you click on a user's profile link it actually takes you back to the profile page.

**To Reproduce**
go to https://silverwaregames.io/user.php?uid=19
click link

**Expected behavior**
its supposed to go to his youtube page.

(THIS MAY HAVE TO DO WITH HTTP vs HTTPS links.)

**Comment by mesosoi** [comment]
Fixed, thank you.

And no, it had nothing to do with http or https. The bug was appearing because of incorrect variable passed into _href=""_.
