### ISSUE TITLE
Dark Mode Link Color

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#115]
In dark mode, links are the same color as the text, can you make them gold or blue so I can tell they are links?

Please and thanks.

**Comment by michaelplzno** [comment]
Doubling down here, can we get this fixed?!?!?!? PLZYES

**Comment by mesosoi** [comment]
Links in posts or everywhere? I did some changes now, you may need to purge the cache, though. Tell me if now is better or not.

**Comment by michaelplzno** [comment]
much improved! thanks.
