### ISSUE TITLE
Success Feedback

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#12]
When you post a post or comment there is a debug popup that is a bit ugly. Make this look cooler, add some confetti or some kind of WOO HOO thing. I can work with you to add SFX or animations or something, but make it look cool and then disappear without having to click a little X.

Also there can be a fail error animation if there is an issue.

**Comment by mesosoi** [comment]
Of course it will be changed, the "debug" or "Done." popups came here from the closed development stage and, in my opinion, are acceptable for the beta stage. Creating a "woo hoo thing" would be overdone, I don't want to add a lot of animations (and SFX, that's sick when sites have a SFX!), I'd just add some ajax instead.

**Comment by mesosoi** [comment]
I'm really beware of adding sound effects, most of websites are completely silent nowadays, it surprises (or even scares) people to see a site plays a sound, if it is not a video/audio streaming service. I guess the only one thing where it's OK to use SFX is notifications.

**Comment by michaelplzno** [comment]
I hear you, don't worry about it too much for now, just something that looks more clean and friendly than the debug window would be a big step up. In DOTS the feedback loop is really smooth and clean, the sfx are minimal:

https://www.youtube.com/watch?v=xKF6KNIh_mw

Your call in the end, just thought it might be nice to give a little sunshine for when people poke at the site and post something.

**Comment by mesosoi** [comment]
> Hi, I'm still seeing the popup window?!?

With the comments, yes, possibly. For posts, no way, I've changed it already.
