### ISSUE TITLE
Saved posts

### ISSUE THREAD

**Issue by mesosoi** [mesosoi/silverwaregames-io-issue-tracker#17]
I plan to add a feature of saving posts for future usage, you'll be able to save any post and then easily re-visit it anytime. The saved posts list will be visible only for you and maximum quantity of saved posts will be limited to 10000. Also I want to add both a full and a compact view (when you see only posts names, authors and dates separated by new line) for saved posts.

**Comment by mesosoi** [comment]
> I'm not sure if I should make a new item for this, but seeing the posts you liked all in a row as its own page would be good too.

Good idea, thank you.

**Comment by michaelplzno** [comment]
Maybe the distinction between a "save" and a "like" is that everyone can see someone's like page, as in, I can visit @abc and see their page of likes, but the "save" page is only visible to the user who made it?

**Comment by mesosoi** [comment]
> Maybe the distinction between a "save" and a "like" is that everyone can see someone's like page, as in, I can visit @abc and see their page of likes, but the "save" page is only visible to the user who made it?

In such a cruel world when they cancel celebrities for likes or comments they post decades ago I don't think that's a good idea to show the page of likes publicly. But even despite that, I don't think that I'd be satisfied if someone would see the list of posts liked by me, just like look, it's not a thing on Facebook or Twitter or anywhere (at least I don't know about it), and also various data scrapers software may do a bad thing by knowing who likes which posts.

I mean, I don't think that somebody's going to run a parser program on the site now, but if we plan that it may (or will) grow, we should think about such sort of things.

**Comment by michaelplzno** [comment]
Yeah, I hear the concern and its reasonable. I think JK Rowling meant to "save" a post instead of "like" it and now everyone hates her.

One of my big goals for this network is that nothing on the site should be posted that hitting like on it will ruin your career. As in, the defining trait of this network is that there isn't "angry rhetorical political takes" clogging the network up, regardless of which political party or ideology you belong to. But I see the point of making things hidden, its reasonable to be concerned. Ideally, I would like to have a way for a profile to spotlight posts they really like as a way of increasing their visibility by pinning someone else's post to their page in some way... but I'm not sure exactly how that would work?

**Comment by michaelplzno** [comment]
Another option is to hide older likes or just clear them out as time passes? I do think, for example, I want all my doodles to survive until I say they should be removed. On the other hand, I'm not sure 100% of the posts I make I'm going to want to live for 40 years. So I'm not so sure about how to handle permanence vs decay. But yes, pinning someone else's post to your own profile is good, like retweets.

**Comment by mesosoi** [comment]
> Another option is to hide older likes or just clear them out as time passes? I do think, for example, I want all my doodles to survive until I say they should be removed. On the other hand, I'm not sure 100% of the posts I make I'm going to want to live for 40 years. So I'm not so sure about how to handle permanence vs decay. But yes, pinning someone else's post to your own profile is good, like retweets.

I already had a thought about auto-removing an account, Google added this feature not so long ago, just like a year ago I guess. And Telegram had this feature since start. I guess I'll add a way to let users delay auto-delete of their posts if they're inactive for, let's say, 10 years. But it's not an easy thing to debug.

And speaking of page of likes, even with auto-removing the old info from there the idea is not good. Parsers software just can open the page once per week/day/hour/minute/second and store the data on their local storages. I know that there are no bad guys on the site, but hackers, malicious users, marketing specialists, spammers, etc, they're already somewhere near to us, developers.

About the retweets, yes I guess I'll add it soon, sounds like a simple idea to release.

**Comment by mesosoi** [comment]
> What about adding a "private mode" to profiles which means that only people who are on network and signed in can see their posts, their posts will never be displayed on the preview or through any page a scraper could see publicly, and all your posts that are over a month old are auto deleted. Users can choose to activate this or not. (This could even be something that shows up like a badge on your name like a lock or a guy in a trench coat.)

Hidden accounts is already a thing, you can hid anyone's account via admin panel (I guess so), it's just not accessible via user's settings page. It's a bit different from what you explained, e.g. here's no badge near to user's name and the old posts ain't being deleted automatically. It is possible to add automatical deletion for posts from hidden account but it's not a really easy thing, I'd possibly delay it as it's both not super-easy and not super-urgent.

**Comment by michaelplzno** [comment]
Yeah, for now this is not a priority, but hidden accounts is probably a good idea.

**Comment by mesosoi** [comment]
> Yeah, for now this is not a priority, but hidden accounts is probably a good idea.

I guess I added a way to hid accounts via admin panel. But if I didn't, I am 100% sure that I added such feature as hidden accounts, in this case I just forgot to change it anywhere (lol).
