### ISSUE TITLE
Enter will post.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#2]
**Is your feature request related to a problem? Please describe.**
Whenever I post I click the post button instead of hitting enter.

**Describe the solution you'd like**
I'd just like it to post when I hit enter.

**Comment by mesosoi** [comment]
Oops, did not know it's still a bug. Will be fixed, thanks.

**Comment by mesosoi** [comment]
A little bit slowly, but I've added this feature. I decided to choose Ctrl+Enter rather than simply Enter.
