### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#20]
Shouldn't take too much effort to add a css change to make the site dark mode based on user choice or OS settings.

**Comment by mesosoi** [comment]
Yes, I guess I'll simply add a css file which will load if user's browser sends a http request which says that their theme is dark.

**Comment by michaelplzno** [comment]
YOU CAN DO IT!

**Comment by mesosoi** [comment]
> YOU CAN DO IT!

Yes I can! Most likely. Anyway, not today. 😛I'm going to post about another update right now.
