### ISSUE TITLE
Timestamps in comments should be displayed relative to post time

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#202]
<img width="1217" alt="image" src="https://github.com/mesosoi/silverwaregames-io-issue-tracker/assets/2665989/812ccaae-b612-4a07-bad9-045d29da6b97">

Cool! -1 minute later

I disagree, super cool! -10 minutes later

Hey, what did I miss? -2 days later

**Comment by mesosoi** [comment]
This one's gonna take some time because I decided to rework the comments system (this means markdown, likes and images)

**Comment by michaelplzno** [comment]
Fine

**Comment by mesosoi** [comment]
I closed this issue, but now I am not sure if I should have. Currently, timestamps in comments are relative to current time, not to the post time. Do you think it would be better for timestamps to use this logic "10 minutes after the post was published" or "2 hours ago the current moment of time"?

**Comment by michaelplzno** [comment]
the timestamp should be based on how long AFTER the post the comment was, so if a post was 1 week ago and the first comment was 1 week and 1 minute ago, it should say "1 minute later" on that post.

**Comment by mesosoi** [comment]
> the timestamp should be based on how long AFTER the post the comment was, so if a post was 1 week ago and the first comment was 1 week and 1 minute ago, it should say "1 minute later" on that post.

You mixed up the comment and post dates here, but I get what you mean. So… are you sure? This sounds absolutely anti-user-friendly, sir ❌☹

**Comment by Miragebell** [comment]
I know what you mean, but are you sure you want that? You're the boss, indeed, but I dislike this idea. Most of the sites use it the way we currently do, so I guess a majority of our users will agree with my opinion.
