### ISSUE TITLE
Like button is too big, look at other social media for size comparison.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#218]

**Comment by michaelplzno** [comment]
Can you mark this as ESSENTIAL FOR NEXT PUBLIC UPDATE?

**Comment by mesosoi** [comment]
Do you like how it looks now? I just made profile pictures bigger, but kept the same size for buttons. Or should I make them smaller, still (don't forget to clear cache)?
