### ISSUE TITLE
Make links in user's profiles look smaller or cut them

### ISSUE THREAD

**Issue by mesosoi** [mesosoi/silverwaregames-io-issue-tracker#26]
In users' profiles they can specify links to different websites, but sometimes it's too big, I plan to use a `<small>` tag for long links or simply cut them and add a ellipsis, and also a `title=` with a full link.

**Comment by michaelplzno** [comment]
might make sense to let the user set the title and the link in separate input fields?

**Comment by mesosoi** [comment]
> #199

I believe this issue is different from the linked one. IIRC here I was mentioning an issue with links in users' profiles were displayed explicitly. In 2023 the profile pages were redone and now the links are hidden under buttons, so this can be closed now.
