### ISSUE TITLE
Down arrow is misaligned in front page.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#261]
<img width="1571" alt="image" src="https://github.com/mesosoi/silverwaregames-io-issue-tracker/assets/2665989/751773b8-5fe4-4b75-999f-d3a99aba3388">

**Comment by mesosoi** [comment]
Fixed. Didn't happen to catch this bug in Firefox but happen to do so in Edge.
