### ISSUE TITLE
Sometimes posts in the discord hook don't display the user's avatar.

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#270]
<img width="215" alt="image" src="https://github.com/mesosoi/silverwaregames-io-issue-tracker/assets/2665989/72b634db-45f0-4a97-a2a1-cbdac578acab">

**Comment by mesosoi** [comment]
This is a bug of the Discord app: sometimes it won't display images from webhooks properly, even though they're located on our server and being passed to Discord when generating a webhook correctly.
