### ISSUE TITLE
Feed is Main Page

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#3]
When silverwaregames.io loads I want to go to the feed as the main page instead of the profile. My profile does not change and I already know what it is.

**Describe the solution you'd like**
Make the default page of swgio to be the feed.

If a user hasn't filled out their profile you can take them there but otherwise just take me to the feed.

**Comment by mesosoi** [comment]
Great, thank you.

I already had the same thought, I just did not know how to describe it in an update note. The site will be updated soon, I'll include that into to-do list.

**Comment by mesosoi** [comment]
Done, thank you.
