### ISSUE TITLE
Something is wrong with firestarter, do I have to change the code?

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#306]
It can't load the images.

**Comment by mesosoi** [comment]
It is probably on the game side. I tried disabling HTTP headers that I thought might have caused this, but the issue is still here.

**Comment by michaelplzno** [comment]
I think this has to do with a google script being blocked. I cannot upload new versions of the games currently but I think I can fix them all pretty quick once upload works.
