### ISSUE TITLE
Price Guessing Game Posts

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#354]
Should be able to post an image like the following:

![food2](https://github.com/mesosoi/silverwaregames-io-issue-tracker/assets/2665989/5eace3b7-e21c-42f8-b85d-7dd44f1f36f4)

And have people guess at the price. Maybe with an international currency rate changer. Reveals the price after 24 hours.

**Comment by Miragebell** [comment]
Michael
