### ISSUE TITLE
Make rules more detailed and formal

### ISSUE THREAD

**Issue by mesosoi** [mesosoi/silverwaregames-io-issue-tracker#36]
As for now the rules are such simple as "Don't be an asshole, that's it" (almost), maybe such a great, grand and a big ~~company~~ corporation as Silverware Games, Inc. should have a more formal rules? Or, at least, more detailed ones?

Mentioning @michaelplzno

**Comment by michaelplzno** [comment]
I think I posted a draft of the rules in discord somewhere, do you want me to post them here?

**Comment by mesosoi** [comment]
> I think I posted a draft of the rules in discord somewhere, do you want me to post them here?

Yes I do
