### ISSUE TITLE
Markups

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#48]
Might make sense to let users add flair to their posts like [code] THIS TEXT IS FORMATTED LIKE CODE [/code] 

Or [green] this text is green [/green]

Low priority but I'm throwing it out there.

**Comment by mesosoi** [comment]
https://github.com/mesosoi/silverwaregames-io-issue-tracker/issues/22 <-- I was planning to rework the posting form here.

**Comment by mesosoi** [comment]
Added few updates ago
