### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by michaelplzno** [mesosoi/silverwaregames-io-issue-tracker#5]
Please make the site work on mobile using the m.silverwaregames.io subdomain!!!

**Comment by mesosoi** [comment]
Sure, but it will take a lot of time to be released, it's probably the hardest idea here, on the issue tracker.

**Comment by michaelplzno** [comment]
Don't worry about getting it perfect for the first launch. You have a tendency to make stuff much better than it needs to be for the first version. If you can get something bare bones working that would be very helpful, even if it is limited in some ways or not perfect. One thing I've noticed is that sometimes a lot of issues we see in the design aren't seen by users, so they may not even be real issues.

**Comment by mesosoi** [comment]
> Don't worry about getting it perfect for the first launch. You have a tendency to make stuff much better than it needs to be for the first version. If you can get something bare bones working that would be very helpful, even if it is limited in some ways or not perfect. One thing I've noticed is that sometimes a lot of issues we see in the design aren't seen by users, so they may not even be real issues.

I can't just create one page and say "hey users, I've created one page", then create another page and say "hey users, I've created a second page", they will get tired soon, this is why my standards for Beta are such. But I still know that Beta and Release have different standards, that's why do we have a "debug" alert while posting, for example... (lol)

**Comment by mesosoi** [comment]
> Obviously you can't release one page at a time, I'm just saying don't worry about getting everything perfect. A big percentage of users I've invited are already turning away from the site because they can't get mobile working so that's also a problem.

Oops, I did not know that. So ok, I'm changing priority of the mobile UI from lower than middle to higher than middle (I don't store ideas anywhere but inside my head and GitHub).

**Comment by michaelplzno** [comment]
BRAVO!
